### ISSUE TITLE
non-.gophermap menus need 'i' prefix for info messages!

### ISSUE THREAD

**Issue by hyperrealgopher** [hyperrealgopher/burrow#37]

**Comment by hyperrealgopher** [comment]
@sternenseemann I think removing 'i' from generated gopher menus that aren't `.gophermap` files breaks them. I'm going to add this back, I think. It sounds like from #1 that this might break something?

**Comment by sternenseemann** [comment]
What are non-`.gophermap` menus? text files which are referenced using the `1`-type?

**Comment by hyperrealgopher** [comment]
Sorry, yes, I mean menus (`1` type) files which are not `.gophermap` files.

**Comment by sternenseemann** [comment]
spacecookie doesn't treat them specially at all since it doesn't know what they are. Thus they are just returned like binary files (and text files) would be. So that is a yes, they need to be valid gopher menu responses.

Note that <https://github.com/sternenseemann/spacecookie/issues/46> may mess with this in the future, but not sure when I'll get around to it.

**Comment by hyperrealgopher** [comment]
Thanks for all the info @sternenseemann, I've started coding a solution.
